ReactiveLists.xcodeproj/project.pbxproj, ReactiveLists.xcodeproj/xcshareddata/xcschemes/ReactiveLists.xcscheme, Tests/FluxCollectionViewDataSourceTests.swift, Tests/FluxCollectionViewModelTests.swift, Tests/FluxTableViewDataSourceTests.swift, Tests/XCTest+Parameterized.swift
Gets the existing tests working as is. Follow-up commits will refactor the tests.
A first step in addressing #2.
=> [Tests] Fix Existing Tests

Example/Base.lproj/Main.storyboard, Example/CollectionViewCells.swift, Example/CollectionViewController.swift, Example/CollectionViewModelProvider.swift, ReactiveLists.xcodeproj/project.pbxproj
Adds the general structure for a CollectionView Example, but the example doesn't work very well, just displays a few blue boxes.  Will chat with the rest of the team to figure out a good structure for the CollectionView example, but want to land this now because its a bunch of structural changes to files / storyboard.
=> [Example] Add UICollectionView Example

scripts/build_docs.sh
=> [Docs] add jazzy docs script

Docs/VISION.md
This is based largely on our recent lunch discussion 😉 
Wonder if I need to elaborate more for folks not familiar with React?
=> [Docs] Initial Vision

Example/Base.lproj/Main.storyboard, Example/TableViewController.swift, Sources/TableViewDataSource.swift, Tests/TableView/TableViewDataSourceTests.swift, Tests/TableView/TableViewDiffingTests.swift
=> Remove ReactiveSwift dependency in TableViewDataSource

Tests/TableView/TableViewDataSourceTests.swift
Documents existing tests, removes some tests that were testing internals, and adds a test that specifies default values.
=> [Tests] Document Test & Improve Coverage

Example/Base.lproj/Main.storyboard, Example/CollectionUserCell.xib, Example/CollectionViewCells.swift, Example/CollectionViewController.swift, Example/TableViewCells.swift, Example/TableViewController.swift, ReactiveLists.xcodeproj/project.pbxproj
Update the CollectionView example to nearly mirror the
TableView example.
Still needs some updates to add section labels / supplementary views, but this should unblock @Ben-G.
=> [Examples] Create functional Collection View example

Example/CollectionViewController.swift, Sources/CollectionViewDataSource.swift, Sources/CollectionViewModel.swift, Sources/TableViewDataSource.swift
Initial implementation of diffing for UICollectionView. This fixes #35.
As expected we’ve duplicated a lot of code for now. That can change down the road as we unify the CollectionView and TableView implementations.
Will add relevant tests in next PR.
=> [Diffing] Automatic Diffing for UICollectionView

Example/Base.lproj/Main.storyboard, Example/CollectionToolCell.xib, Example/CollectionViewCells.swift, Example/CollectionViewController.swift, Example/Models.swift, Example/TableViewCells.swift, Example/TableViewController.swift, ReactiveLists.xcodeproj/project.pbxproj
Make Examples Construction Themed
=> [Examples] Make Examples Construction Themed

ReactiveLists.xcodeproj/project.pbxproj, Tests/CollectionView/CollectionViewDataSourceMocks.swift, Tests/CollectionView/CollectionViewDiffingTests.swift
Adds counterpart of TableView diffing tests for CollectionView. Again, a lot of redundancy that can be removed in future.
=> [Tests] Add CollectionView Diffing Tests

ReactiveLists.xcodeproj/project.pbxproj, Sources/TableViewDriver.swift, Tests/TableView/TableViewDiffingTests.swift, Tests/TableView/TableViewDriverTests.swift, Tests/TableView/TableViewMocks.swift
Only rename for now (+deletion of dead code), to avoid conflicts with other work in progress.
=> [Rename] TableViewDataSource -> TableViewDriver

Example/CollectionViewController.swift, Example/TableViewController.swift, Sources/CollectionViewDriver.swift, Sources/TableViewDriver.swift
Make automatic diffing true by default
=> [Diffing] Make automatic diffing true by default

Sources/CollectionViewDriver.swift, Sources/TableViewDriver.swift, Tests/CollectionView/CollectionViewDriverTests.swift, Tests/TableView/TableViewDiffingTests.swift, Tests/TableView/TableViewDriverTests.swift
Symmetric to CollectionViewDriver documentation.
Also fix some issues that were introduced into the unit tests by enabling automatic diffing by default.
=> [Docs] Document TableViewDriver

Example/CollectionViewCells.swift, Sources/CollectionViewDriver.swift, Sources/CollectionViewModel.swift, Sources/TableViewModel.swift, Tests/CollectionView/CollectionViewDriverTests.swift, Tests/Fixtures/TestCollectionViewModels.swift
Similar changes as for TableViewModel in earlier PR. Some more cleanup / docs left.
=> [Cleanup] Improve CollectionViewModel - Part I

.github/CONTRIBUTING.md
=> [Docs] Add Contributing Guidelines

ReactiveLists.xcodeproj/project.pbxproj, Sources/CollectionViewDriver.swift, Sources/CollectionViewModel.swift, Sources/TableViewDriver.swift, Tests/CollectionView/CollectionViewDriverTests.swift, Tests/TableView/TableViewDriverTests.swift
=> [Clean Up] Minor clean up and refactor

Dangerfile
Test That Danger Swiftlint Works
=> [Danger] Test That Danger Swiftlint Works

ReactiveLists.xcodeproj/project.pbxproj, Sources/CollectionViewDriver.swift, Sources/TableViewDriver.swift, Sources/UICollectionView+Extensions.swift, Sources/UITableView+Extensions.swift
- remove lots of dupe code
- clean up
Next up: adding `ViewRegistrationMethod` to cell view models
#18
=> Cleanup view registration code, prep for auto-registration for cells

Guides/Getting Started.md, README.md
=> [Getting Started] Add a Getting Started Guide

Gemfile, ReactiveLists.podspec
=> [Podspec] Set Swift Version to 4.0.0

README.md
Minor formatting fixes and content changes.
=> [Readme] Minor Changes

Example/CollectionViewCells.swift, Example/CollectionViewController.swift, Sources/CollectionViewDriver.swift, Sources/CollectionViewModel.swift, Sources/UICollectionView+Extensions.swift, Sources/UITableView+Extensions.swift, Tests/CollectionView/CollectionViewDriverDiffingTests.swift, Tests/Fixtures/TestCollectionViewModels.swift
=> Auto-register collection cells. Close #18

Example/CollectionViewController.swift, Sources/CellContainerViewProtocol.swift, Sources/CollectionViewDriver.swift, Sources/SupplementaryViewInfo.swift, Sources/TableViewDriver.swift, Tests/CollectionView/CollectionViewDriverTests.swift, Tests/CollectionView/CollectionViewModelTests.swift, Tests/Fixtures/TestCollectionViewModels.swift, Tests/Fixtures/TestTableViewModels.swift, Tests/TableView/TableViewDriverTests.swift, Tests/TableView/TableViewModelTests.swift
- Make `SupplementaryViewInfo` own a `ViewRegistrationInfo` like cell models
- Update / fix tests
=> Supplementary view fixes / improvements

README.md
Add a link to the announcement blog post.
=> [README] Link to Announcement Post

README.md
Just a small README improvement 😉
=> CocoaPods capitalization on README

.travis.yml, ReactiveLists.xcodeproj/project.pbxproj
=> Update travis to use Xcode 9.4

CHANGELOG.md, ReactiveLists.podspec
- Updates CHANGELOG to include info about fix from #128 
- Updates the podspec
- Makes 0.2.0 the "next" release
=> Prepare 0.1.3 release

CHANGELOG.md, ReactiveLists.podspec
This updates the podspec and changelog for the 0.1.4 release.
=> Prepare for 0.1.4 release

CHANGELOG.md, ReactiveLists.podspec
This prepares ReactiveLists for the 0.2.0 release.
=> Prepare for 0.2.0 release

.swiftlint.yml, CHANGELOG.md, Podfile, Podfile.lock, Pods/Manifest.lock, Pods/Pods.xcodeproj/project.pbxproj, Tests/TableView/TableViewDriverTests.swift
=> Upgrade swiftlint 0291

CHANGELOG.md, Sources/TableViewDriver.swift, Sources/TableViewModel.swift, Tests/TableView/TableViewDriverTests.swift, Tests/TableView/TestTableViewModels.swift
=> Default row height API (#41)

.travis.yml, CHANGELOG.md
Upgrades Travis to Xcode 10.2
Issue fixed: #159
=> [CI] Upgrade to Xcode 10.2

.github/workflows/ci.yml
This introduces caching in GitHub Actions so that we don't re-resolve our Pods each time.
=> [CI] GitHub Actions Cocoapods Caching

Podfile
Uses CocoaPods CDN to see if we can
resolve the specs repo a bit faster on
CI builds.
=> [CI] Use CocoaPods CDN

CHANGELOG.md, ReactiveLists.podspec
This prepares ReactiveLists for 0.6.0.
=> Prepare 0.6.0 release

CHANGELOG.md, ReactiveLists.podspec, Sources/TableViewDriver.swift, Sources/TableViewModel.swift, Tests/TableView/TableViewModelTests.swift, Tests/TableView/TestTableViewModels.swift
=> Add TableSectionPosition + prepare release

ReactiveLists.podspec, Sources/TableViewDriver.swift
Forgot to set the prefetch data source.
=> Actually set the prefetch data source

Sources/TableViewDriver.swift, Sources/TableViewModel.swift, Tests/TableView/TableViewDriverTests.swift, Tests/TableView/TestTableViewModels.swift
Added Support to deselect cell.
=> Support to deselect cell.

ReactiveLists.podspec
Updated Podspec to recent version
=> Bumped version to 0.8.1

.github/workflows/ci.yml, CHANGELOG.md
Attempt to fix the CI run by updating xcode and device versions
=> Attempt to fix CI
