Tests/FluxCollectionViewModelTests.swift, Tests/FluxTableViewModelTests.swift, Tests/TestFluxCollectionViewModels.swift, Tests/TestFluxTableViewModels.swift
First iteration of cleanups up for review:
- Eliminate the word “random” from generated test data
- Eliminate helper functions that obfuscate underlying types (`path()` instead of `IndexPath()` - needs to be fixed in more places)
- Add docs to tests that describe their intent
- If tests contain multiple assertions (which we’ll often avoid) order them in a logical way
=> [Tests] Cleanup

ReactiveLists.xcodeproj/project.pbxproj, Tests/CollectionView/CollectionViewDataSourceMocks.swift, Tests/CollectionView/CollectionViewDataSourceTests.swift, Tests/Fixtures/TestTableViewModels.swift, Tests/TableView/TableViewDataSourceMocks.swift, Tests/TableView/TableViewDataSourceTests.swift, Tests/TableView/TableViewMocks.swift
- Colocates mocks and stubs for different tests
- Rewrites table view test that tests that cells receive correct callbacks (now uses dedicated mocks instead of global state)
This PR is dependent on #33
=> [Test] Cleanup Mock Usage

Sources/CollectionViewDataSource.swift, Sources/CollectionViewModel.swift, Sources/TableViewDataSource.swift, Sources/TableViewModel.swift
Noticed this while refactoring tests. Optionality of sections was unnecessary, as, in this case, the absence of sections can better be described by an empty array.
This cleans up the implementation quite a bit.
=> [Refactor] Make Sections on Models Non-Optional

Sources/TableViewDataSource.swift, Tests/TableView/TableViewDataSourceTests.swift, Tests/TableView/TableViewMocks.swift
- remove `headersOnScreen`
- remove `footersOnScreen`
- use UIKit APIs instead
- update tests
=> [TableView] remove "on screen" header/footer state. Close #38

ReactiveLists.podspec
Adds an initial podspec that allows development of the `ReactiveLists-ReactiveSwift` extension.
=> [Pod] Add Initial Podspec

Example/CollectionViewCells.swift, Example/CollectionViewController.swift, Example/CollectionViewHeaderView.xib, Example/TableViewController.swift, ReactiveLists.xcodeproj/project.pbxproj
Add Collection View Supplementary Views
=> [Example] Add Collection View Supplementary Views

Sources/TableViewDriver.swift
- refine access control
- remove `open`
- make class `final`
- add `// MARK:`s
- organize `DataSource` and `Delegate` methods in extensions
- add `/// :nodoc:` for data source and delegate methods so jazzy ignores them
=> [TableDriver] Cleanup and organization

Example/CollectionViewCells.swift, Example/TableViewCells.swift, ReactiveLists.xcodeproj/project.pbxproj, Sources/CollectionViewModel.swift, Sources/TableViewDriver.swift, Sources/TableViewModel.swift, Sources/Typealiases.swift, Tests/CollectionView/CollectionViewDriverDiffingTests.swift, Tests/Fixtures/TestCollectionViewModels.swift, Tests/Fixtures/TestTableViewModels.swift, Tests/TableView/TableViewDiffingTests.swift, Tests/TableView/TableViewDriverTests.swift, Tests/TableView/TableViewMocks.swift
- `applyViewModelToCell` no longer has a return value. That return value was never used and could never be used, as that method is called to update a cell that is currently on screen. The API was misleading as it seemed possible to return an entirely new cell.
- Dropped “Closure” from all `TableViewCellModel` properties as that was redundant
- Documented `TableViewCellModel`
- Moved all typealiases into one file
=> [Cleanup/Docs] Cleanups for Model Layer

Example/CollectionViewController.swift, Example/TableViewController.swift, Sources/CollectionViewModel.swift, Sources/TableViewModel.swift, Tests/CollectionView/CollectionViewDriverDiffingTests.swift, Tests/CollectionView/CollectionViewDriverTests.swift, Tests/CollectionView/CollectionViewModelTests.swift, Tests/TableView/TableViewDiffingTests.swift, Tests/TableView/TableViewDriverTests.swift, Tests/TableView/TableViewModelTests.swift
Changes the names of all types that are view models to be consistent. Removes namespace nesting which was inconsistent.
=> [Naming] Use *ViewModel Consistently

Sources/AccessibilityFormats.swift, Sources/TableViewDriver.swift, Sources/TableViewModel.swift, Sources/Typealiases.swift, Tests/TableView/TableViewDriverTests.swift, Tests/TableView/TableViewModelTests.swift
- Make `SectionModel.cellViewModels` **not** optional, can use `isEmpty` instead
- Remove `typealias Section`. Only used once and provides no value.
=> Table cleanup and fix empty state, #48

Example/CollectionViewController.swift, ReactiveLists.xcodeproj/project.pbxproj, Sources/CollectionViewDriver.swift, Sources/SupplementaryViewInfo.swift, Sources/ViewRegistrationMethod.swift, Tests/Fixtures/TestCollectionViewModels.swift, Tests/Fixtures/TestTableViewModels.swift
This still needs all kinds of work to correctly model how collection view supplementary views work, but this is a start.
We're artificially (and implicitly) restricted to headers and footers. We'll probably have to keep this limitation for 1.0.
This aims to make a more general transition easier.
- Make `kind` a property of `SupplementaryViewInfo`
- Make `ViewRegistrationMethod` a proper type on its own (which we can use for cell registration in #18)
=> Cleanup supplementary views, part 1, close #56

Sources/AccessibilityFormats.swift, Sources/CollectionViewDriver.swift, Sources/CollectionViewModel.swift, Sources/Diffing.swift, Sources/SupplementaryViewInfo.swift, Sources/TableViewDriver.swift, Sources/TableViewModel.swift, Sources/Typealiases.swift, Tests/CollectionView/CollectionViewDriverTests.swift, Tests/CollectionView/CollectionViewModelTests.swift
All public symbols that are considered part of the core API are now documented.
This commit suppresses documentation for APIs that will be removed in future releases.
+ minor code change, making `cellViewModels` on `CollectionViewModel` non-optional.
=> [Docs] Complete Public API Documentation

ReactiveLists.xcodeproj/project.pbxproj, Sources/CellContainerViewProtocol.swift, Sources/CellParentViewProtocol.swift, Sources/CollectionViewModel.swift, Sources/SupplementaryViewInfo.swift, Sources/TableViewModel.swift, Sources/UICollectionView+Extensions.swift, Sources/UITableView+Extensions.swift, Sources/ViewRegistrationInfo.swift
Rather than copy-pasta table view code for collection view, let's unify them.
This introduces `CellParentViewProtocol` to reduce duplication in auto-registering cells. It unifies the APIs of tables and collections.
On top of this, we add `ReusableCellProtocol` and `ReusableSupplementaryViewProtocol` to unify our cell view models and supplementary view models.
Now there's a single API for registering cells automatically.
All work based on:
https://github.com/jessesquires/JSQDataSourcesKit/blob/develop/Source/ReusableViewConfig.swift
Almost completes #18, starts initial work on #46
=> Auto cell registration + unify table and collection views

Example/CollectionViewCells.swift, Example/CollectionViewController.swift, ReactiveLists.xcodeproj/project.pbxproj, Sources/CellContainerViewProtocol.swift, Sources/CollectionViewModel.swift, Sources/ReusableCellViewModelProtocol.swift, Sources/TableViewModel.swift, Sources/UICollectionView+Extensions.swift, Sources/ViewRegistrationInfo.swift, Tests/CollectionView/CollectionViewDriverDiffingTests.swift, Tests/CollectionView/CollectionViewDriverTests.swift, Tests/CollectionView/CollectionViewModelTests.swift, Tests/Fixtures/TestCollectionViewModels.swift
- Rename `ReusableCellProtocol` --> `ReusableCellViewModelProtocol`
Remove superfluous "view" in names:
- Rename `CollectionViewCellViewModel` --> `CollectionCellViewModel`
- Rename `CollectionViewSupplementaryViewModel` --> `CollectionSupplementaryViewModel`
- Rename `CollectionViewSectionViewModel` --> `CollectionSectionViewModel`
- Add docs for `ViewRegistrationInfo`
=> Clean up, docs, renaming

Example/TableViewCellModels.swift, Example/TableViewController.swift, Sources/TableViewDriver.swift, Sources/TableViewModel.swift, Sources/UITableView+Extensions.swift, Tests/Fixtures/TestTableViewModels.swift, Tests/TableView/TableViewDiffingTests.swift, Tests/TableView/TableViewDriverTests.swift, Tests/TableView/TableViewMocks.swift, Tests/TableView/TableViewModelTests.swift
- TableViewCellViewModel --> TableCellViewModel
- TableViewSectionHeaderFooterViewModel --> TableSectionHeaderFooterViewModel
- TableViewSectionViewModel --> TableSectionViewModel
=> Table component renames, similar to #104

Sources/TableViewModel.swift, Tests/TableView/TableViewModelTests.swift
Issue fixed: A rare production issue where UIKit gives us a bad IndexPath.
=> Check that the IndexPath is valid before using it

CHANGELOG.md, Sources/TableViewDriver.swift
Allows the selection of a different row animation. The `automatic` animation can look a bit odd sometimes. For example when inserting a section the cells come in from the left.
=> Allow selection of row animtions for table view

CHANGELOG.md, Sources/CollectionViewModel.swift, Sources/TableViewModel.swift
- Section and cell view models are now diffable by default.
They have default values for `diffingKey`, but clients should be customizing these for their needs.
- `CollectionSectionViewModel` protocol now inherits from `DiffableViewModel` protocol
- `CollectionCellViewModel` protocol now inherits from `DiffableViewModel` protocol
- ` TableSectionViewModel` protocol now inherits from `DiffableViewModel` protocol
- `TableCellViewModel` protocol now inherits from `DiffableViewModel` protocol
Closes #114
=> [Fix] Make section and cell view models diffable by default

CHANGELOG.md, Sources/TableViewDriver.swift, Sources/TableViewModel.swift, Tests/TableView/TableViewDriverTests.swift, Tests/TableView/TableViewModelTests.swift
This is seems to be a vestigial aspect of the framework from early PlanGrid days.
We don't use this anywhere in PlanGrid.
To achieve this sort of "collapsing" behavior, you'd capture this state elsewhere in your model, and simply regenerate your SectionModel with zero CellViewModels.
This is how we currently do this in PlanGrid.
And, I think this makes more sense to generate full state changes, rather than "hiding" a section. (i.e., this is sort of a hack)
Further, this is complicates notions of "empty/nil state" (see #48 and IP-3275) and I want to remove that complexity.
Closes #120
=> Remove TableSectionViewModel.collapsed, close #120

CHANGELOG.md, Example/CollectionViewController.swift, Sources/CollectionViewModel.swift, Sources/TableViewModel.swift, Tests/CollectionView/CollectionViewDriverDiffingTests.swift, Tests/CollectionView/CollectionViewModelTests.swift, Tests/Fixtures/TestCollectionViewModels.swift, Tests/Fixtures/TestTableViewModels.swift, Tests/TableView/TableViewDriverTests.swift, Tests/TableView/TableViewModelTests.swift
- Fix `TableViewModel.isEmpty` calculation
- Add `CollectionSectionViewModel.isEmpty`
- Add `CollectionViewModel.isEmpty`
- Remove undocumented initializers for `CollectionSectionViewModel` (the ones that received `headerHeight:` and/or `footerHeight:`)
These were causing ambiguous naming errors. Also, we don't use them in PlanGrid.
Closes #48
=> Fix isEmpty calculations, add property to collection models

CHANGELOG.md, ReactiveLists.xcodeproj/project.pbxproj, Sources/CollectionViewDriver.swift, Sources/TableViewDriver.swift, Tests/CollectionView/CollectionViewDriverDiffingTests.swift, Tests/CollectionView/CollectionViewMocks.swift, Tests/CollectionView/TestCollectionViewModels.swift, Tests/TableView/TableViewDiffingTests.swift, Tests/TableView/TableViewMocks.swift, Tests/TableView/TestTableViewModels.swift
=> Fix crash when diffing to/from empty/nil states to/from non-empty/nil states

CHANGELOG.md, Sources/TableViewDriver.swift
This calls `reloadData` on `self.tableView` when diffing is disabled. This ensures that the `UITableView` is in sync with new data model before attempting to call methods on `UITableView` that would require the data model to be in sync to get correct results (i.e. `cellForRow(at:)`). This prevents crashing in `cellForRow(at:)` when `UITableView` asks for cells near a user-requested (programmatically), when the data model may not actually have the data for that cell.
=> reloadData if diffing before refreshViews if diffing is disabled

Tests/CollectionView/CollectionViewDriverDiffingTests.swift
This fixes a test that was failing due to a `UICollectionView` bug.
=> Fix test for UICollectionView section change

CHANGELOG.md, Sources/TableViewDriver.swift
=> reloadData if diffing before refreshViews if diffing is disabled (#127)

CHANGELOG.md, Sources/CollectionViewDriver.swift, Sources/CollectionViewModel.swift, Sources/TableViewDriver.swift, Sources/TableViewModel.swift, Tests/CollectionView/CollectionViewModelTests.swift, Tests/TableView/TableViewModelTests.swift
This adds `ifExists:` to the subscript methods that return an `Optional`. This will help, if/when we move forward with `Collection` conformance for `TableViewModel` and `CollectionViewModel` because `Collection` subscript methods have a non-`Optional` return type.
=> Add ifExists: to subscripts that return optional

CHANGELOG.md, Sources/CollectionViewDriver.swift, Sources/TableViewDriver.swift, Tests/CollectionView/CollectionViewDriverTests.swift, Tests/TableView/TableViewDriverTests.swift
This fixes a regression where we started storing empty values for the first non-nil value (i.e. the first value to start diffing from). This caused crashes in some scenarios.
=> Don't store an empty model for the first non-nil differ

CHANGELOG.md, Sources/CollectionViewModel.swift, Sources/TableViewModel.swift, Tests/CollectionView/CollectionViewModelTests.swift, Tests/TableView/TableViewModelTests.swift
This adds `Collection` conformance to *`SectionModel` types, which eases upgrading to Swift-based, non-Dwifft diffing (most diff `Collection`s).
=> Add Collection conformance for *SectionModel types

Sources/Diffing.swift
=> Add docs to Diffing.swift

CHANGELOG.md, Example/CollectionViewController.swift, Example/TableViewController.swift, Sources/CollectionViewModel.swift, Sources/Diffing.swift, Sources/TableViewModel.swift, Tests/CollectionView/CollectionViewDriverDiffingTests.swift, Tests/CollectionView/CollectionViewDriverTests.swift, Tests/CollectionView/CollectionViewModelTests.swift, Tests/TableView/TableViewDiffingTests.swift, Tests/TableView/TableViewDriverTests.swift, Tests/TableView/TableViewModelTests.swift
Issue fixed: n/a
As discussed with @benasher44 and @noahsark769, this updates the initializers for `TableSectionViewModel` and `CollectionSectionViewModel` so that the `diffingKey` argument is _required_. 
This prevents accidental misuse of the automatic diffing API, which is possible if you rely on the current default parameter value. 😅 
No new behavior here, just a breaking API change. Tests are updated accordingly (no new ones).
Previously `diffingKey` was the **last** parameter in each initializer. I chose to make it the **first** in the argument list:
* The Swift [API design guidelines](https://swift.org/documentation/api-design-guidelines/) tell us:
> Prefer to locate parameters with defaults toward the end of the parameter list
* If we keep `diffingKey` close to the bottom as the …
=> Make section `diffingKey` parameter required

CHANGELOG.md, Podfile, Podfile.lock, Pods/DifferenceKit/README.md, Pods/DifferenceKit/Sources/Algorithm.swift, Pods/DifferenceKit/Sources/AnyDifferentiable.swift, Pods/DifferenceKit/Sources/ArraySection.swift, Pods/DifferenceKit/Sources/Changeset.swift, Pods/DifferenceKit/Sources/ContentEquatable.swift, Pods/DifferenceKit/Sources/Differentiable.swift, Pods/DifferenceKit/Sources/ElementPath.swift, Pods/DifferenceKit/Sources/Extensions/UIKitExtension.swift, Pods/DifferenceKit/Sources/StagedChangeset.swift, Pods/Manifest.lock, Pods/Pods.xcodeproj/project.pbxproj, Pods/Target Support Files/DifferenceKit/Info.plist, ReactiveLists.podspec
This upgrades DifferenceKit to 0.7.2. They dropped support for Swift 4.1 in 0.7, which reportedly led to some performance gains 🎉.
=> Upgrade DifferenceKit to 0.7.2

CHANGELOG.md, Sources/CollectionViewModel.swift, Sources/TableViewModel.swift
Uses allSatisfy() in places where
we would use first(where:) == nil
=> [Scout] Use allSatisfy()

CHANGELOG.md, Sources/TableViewDriver.swift, Sources/TableViewModel.swift
This adds tableview support for the [`UISwipeActionsConfiguration`](https://developer.apple.com/documentation/uikit/uiswipeactionsconfiguration) API, which was introduced in iOS 11. This should be used to replace usage of the `UITableViewRowAction` API, which will be deprecated in iOS 13.
Issue fixed: none
=> Add support for UISwipeActionsConfiguration

Sources/Diffing.swift, Sources/TableViewModel.swift
In #167, I forgot to make the default implementations for the `TableViewCellModelEditActions` properties `public`. Thus, they were only the defaults within ReactiveLists.
Also, fixes a (new?) lint warning.
=> Make TableViewCellModelEditActions default implementations public

Tests/TableView/TableViewDriverTests.swift
Adds an explicit test for the default `rowHeight` behavior in `UITableView`s.
=> [Tests] Add test coverage for default UITableView rowHeight

CHANGELOG.md, Example/CollectionViewCells.swift, Sources/CollectionViewDriver.swift, Sources/CollectionViewModel.swift, Tests/CollectionView/CollectionViewDriverTests.swift, Tests/CollectionView/TestCollectionViewModels.swift
Issue fixed: #49
This introduces a new property `itemSize` to `CollectionCellViewModel` so that individual cells can be sized when collection views are used with flow layouts. Semantics mirror the equivalent `rowHeight` property used for `TableCellViewModel`.
=> Add support for individual UICollectionViewCell sizing

CHANGELOG.md, Sources/CollectionViewDriver.swift, Sources/CollectionViewModel.swift, Tests/CollectionView/CollectionViewDriverTests.swift, Tests/CollectionView/TestCollectionViewModels.swift
This replaces `CollectionCellViewModel.itemSize` with a new protocol, `FlowLayoutCollectionCellViewModel`.
#177 was a naive first attempt at implementing #49. However, I was thinking through actual usage of this API (also was inspired by #54), and I think in most situations it would be helpful to have access to the collection view and layout objects when specifying a cell size (users can just ignore the view and layout if unneeded). Those params are already passed into the `UICollectionViewDelegateFlowLayout` method where `itemSize` is used, so it's easy to expose access to ReactiveLists clients.
Additionally, `itemSize` is only actually useful if a collection view is used with `UICollectionViewFlowLayout`. Making this explicit with a different protocol will be clearer than having a …
=> Incorporate FlowLayout delegate params into collection cell itemSize API

Sources/Diffing.swift
This fixes an ambiguity with Swiift.Collection and a Collection typealias in DifferenceKit.
=> Fix building in Xcode 11.4

ReactiveLists.podspec, ReactiveLists.xcodeproj/project.pbxproj, Sources/CellContainerViewProtocol.swift, Sources/Diffing.swift, Sources/ReusableCellViewModelProtocol.swift, Sources/TableCellViewModelDataSource.swift, Sources/TableViewDriver.swift, Sources/TableViewModel.swift, Sources/UITableView+Extensions.swift, Tests/TableView/TableViewDiffingTests.swift, Tests/TableView/TableViewLazyDiffingTest.swift, Tests/TableView/TableViewMocks.swift, Tests/TableView/TableViewModelTests.swift
Allows non-Array data sources, so that we can lazy-load
=> Create datasource for cells to make lazy-loading possible

ReactiveLists.podspec, Sources/Diffing.swift, Sources/TableCellViewModelDataSource.swift, Sources/TableViewDriver.swift
Ensure we skip sections that become/missing invalid in prefetch calls
=> Skip missing sections

ReactiveLists.podspec, Sources/Diffing.swift, Sources/TableCellViewModelDataSource.swift
- Cache view registration info across diffs
- Cache startIndex and endIndex to avoid re-querying original data source for count
=> Improve datasource caching

ReactiveLists.podspec, Sources/TableViewDriver.swift
- Fix an edge case where refresh of visible cells is still needed after a diff
=> Fix refresh edge case

ReactiveLists.podspec
The DifferenceKit call that creates the ChangeSet is causing our problems where an unexpected cell type is given to a ViewModel. Checking if updating their pod fixes the problem.
=> Update differencekit dependency

ReactiveLists.podspec, Sources/Diffing.swift
Fixed a diffing key issue inside DiffableTableCellViewModelProxy.
Changed from static to instance because it was giving all off screen models the same diffing key.
There is a scenario where some models that are off screen, are about to come on screen, and when they all share a diffing key they get mixed up and the StagedChangeset ends up with some unnecessary information.
This was ok on Xcode 12, the DifferenceKit reload, which does a performBatchUpdate, sets the new table data, and modifies the rows, handled the extra info.
On upgrading to Xcode 13 the extra information in the StagedChangeset caused the performBatchUpdates to associate some cells with the wrong model.
In PlanGrid, on Xcode 13, the wrong cells associated with wrong models could cause a crash. On Xcode 12, the crash part …
=> Fixed diffing keys issue

.github/workflows/ci.yml, ReactiveLists.podspec, Sources/TableViewDriver.swift, Sources/TableViewModel.swift, Sources/Typealiases.swift
Currently when using the tableview driver it is not possible to handle scroll related events, so in this PR I am adding the conformance for the UIScrollViewDelegate protocol and a closure for the didScroll method only. The other methods are not considered for now.
=> Add ScrollViewDelegate conformance

CHANGELOG.md, ReactiveLists.podspec, ReactiveLists.xcodeproj/project.pbxproj, Sources/CollectionCellViewModelDataSource.swift, Sources/CollectionViewDriver.swift, Sources/CollectionViewModel.swift, Sources/Diffing.swift, Sources/UICollectionView+Extensions.swift, Tests/CollectionView/CollectionViewLazyDiffingTests.swift
Adding a CollectionCellViewModelDataSource to to make lazy-loading for CollectionView, currently we only support this for TableViews. This will allow to do pagination on Collection Views too.
[Currently a WIP]
=> Create datasource for cells to make lazy-loading possible for collections

CHANGELOG.md, ReactiveLists.podspec, Sources/TableViewDriver.swift
Some jumping behavior was starting to pop up on reloads. Odd header/footer heights were causing this. Giving an estimated row height helps to fix the issue. UITableView also doesn't like that `leastNormalMagnitude` number, which also causes jumping on reload. The default value is now 0.0 for headers/footers
=> Fix row height issues

CHANGELOG.md, ReactiveLists.podspec, Sources/TableViewDriver.swift
Made cell row heights static.  This was causing performance issues on large table views (1 million + cells)
- [ x ] I added an entry to the `CHANGELOG.md` for any breaking changes, enhancements, or bug fixes.
- [ x ] I have reviewed the [contributing guide](https://github.com/plangrid/ReactiveLists/blob/master/.github/CONTRIBUTING.md)
=> return default row height instead of a calculation for estimated height

CHANGELOG.md, ReactiveLists.podspec, Sources/TableViewDriver.swift
* add optional `lightweightDiffing` option for use with very large but largely static lists
Issue fixed: #
For forms we found that performance is massively better with automatic diffing disabled for large forms. Unfortunately, doing a full reload of tableview data causes text fields to resign focus which is a bad experience for end users.
Lightweight diffing is an option I'd like to explore for forms since we don't frequently add/remove/move sections/cells.
=> feat(TableViewDriver): allow lightweightDiffing
